services:
  - type: web
    name: cookie-forecast-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: backend/automation/cookie-drive-bot.json
      - key: RENDER_DATABASE_URL #Set as Environment Variable on render

jobs:
  - type: cron
    name: run-cookie-sales-pipeline
    env: python
    schedule: "0 4 * * 1"  # every Monday at 4 AM UTC
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/automation/run_pipeline.py
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: backend/automation/cookie-drive-bot.json
      - key: RENDER_DATABASE_URL #Set as Environment Variable on render
  