name: Upload Cookie Mapping to Render DB

on:
  workflow_dispatch:  # Manual trigger

jobs:
  upload-cookie-mapping:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: service_account.json
      RENDER_DATABASE_URL: ${{ secrets.RENDER_DATABASE_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install PyDrive2 openpyxl

      - name: Create service account key file
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > service_account.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

      - name: Upload cookie mapping to Render DB
        run: python backend/automation/upload_cookie_mapping_to_db.py
