name: Cookie Sales Render Upload with cookie Mapping

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: service_account.json
      RENDER_DATABASE_URL: ${{ secrets.RENDER_DATABASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install PyDrive2 gspread oauth2client

      - name: Create service account key file
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > service_account.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

      - name: Run cookie sales pipeline and upload to Render DB
        run: python backend/automation/run_pipeline.py

      - name: Upload cookie mapping tables to Render DB
        run: python backend/automation/upload_cookie_mapping_to_db.py
